### PR TITLE
Add note to PPA (Issue #56)

### PR DESCRIPTION
**Pull request by brennanhm**
Hi :)

I've added functionality so that when you right-click on a PPA, there's an option to add a note. This will help users remember why they added a particular PPA to their system.

**Add a note**: Right-click on the PPA and select "Note". Type your note into the dialog box and click "OK". A comment is added to the PPA's source file and it appears in brown text beside the PPA name in the GUI.
**Modify a note**: Open note, make changes, and click OK. The PPA's source file is updated with the altered comment.
**Delete a note**: Open note, delete all the text, and click OK. The comment is removed from the source file.

To accomodate this feature, only the hashes on the left side of the PPA source file are removed when instantiating a repository object. This allows for notes/comments to be identified. 

I've been able to test it successfully with multiple PPAs on my own development machine.

Feedback welcome!

### CODE REVIEW

**Comment by brennanhm** [comment]
I've added this to [my PPA](https://launchpad.net/~brennanhm/+archive/ubuntu/linuxmint) for anyone who would like to try it out.

**Comment by clefebvre** [comment]
Hi,

First of all, thanks for working on this and for this PR.

It's a pity we didn't talk about it before you worked on it though.

I like the idea of making sources more memorable but I don't think this is the best way...

Little things:

- The note appears both beside the name and beside the URL (no need for the latter)
- The feature isn't discoverable easily (more on that later)
- The note dialog is fugly (missing margins for instance)
- In the dialog, cancel and OK are in the wrong place.. Ok should be on the right
- In the dialog, pressing Enter should validate

General considerations:

As we're adding more and more PPA features... the UI is getting a little busy. I'd prefer it if we introduced a new PPA screen. In there we could modify the URL, see the list of packages, edit a description (which would appear in the main PPA list) etc..

**Comment by brennanhm** [comment]
Thank you for the feedback. I'll watch out for those little things in the future.

I had hoped to spend more time on this issue this week, but some unexpected events have occurred and I haven't been able to find the time.

As soon as I can, I'll try to add the functionality you have suggested to the PPA screen and make another PR.

**Comment by clefebvre** [comment]
Don't hesitate to join us on #linuxmint-dev (irc.spotchat.org) so we can chat about this.

I'll close this PR in the meantime.

**Pull request closed without merging**
