### PR TITLE
Added pkexec support

### PR DESCRIPTION
**Pull request by dg1727**
See https://github.com/linuxmint/mintsources/issues/75

### CODE REVIEW

**Comment by clefebvre** [comment]
Hi @dg1727,

First of all, thanks for doing this.

There's a lot for me to test here, and not only in Mint but LMDE and for all editions, so this might take a while. But I'll review it and I hope we'll benefit from it and see it merged.

I'd like to ask you to make your changes as modular as possible, so we can merge things little by little and not have items blocked by others which are awaiting testing.

For instance here you've made multiple changes which aren't related to one another.

A couple of small things first:
 - xgettext: --its and --language are mutually exclusive
 - Please don't parse the glade file. This tool sets the string within the code directly. You can do that if you want, and if you do you need to remove a lot of code in Python, but in a separate PR, it will need to be tested differently.

I'm not comfortable with switching mint-common's which-launcher to pkexec. It's a change which would require a lot of testing, across many apps and many environments.

Instead, I would recommend adding a python function to mint-common, that tools could use. That would allow us to merge that without impact into mint-common, and then to switch apps one by one individually.

It would also be more elegant than calling an executable and parsing its result.

So instead of:

```
which_launcher = "/usr/lib/linuxmint/common/mint-which-launcher.py"
launcher_query = [which_launcher, "-p", sentence, "-i", icon]
launcher = get_output_uni(launcher_query)
```

we'd have something like:

```
import linuxmint
launcher = linuxmint.get_launcher()
```

or even better:

```
import linuxmint
mycommand = ['/usr/bin/blah', 'somearg']
linuxmint.launch_with_elevated_privileges(mycommand, mymessage, myicon)
```

I would recommend this launcher checks for the presence of the polkit daemon, not just the pkexec executable. I'm under the impression that pkexec won't work if the polkit agent is down. I've seen it not being launched in some DEs in the past due to problems with onlyshowin and/or session definitions.

Last but not least, please don't translate anything that isn't visible or that doesn't need translating. At the moment if I run makepot, I see msgids for the polkit description (which isn't visible in the dialog), for "Linux Mint", for the executable name, ... even for "true" :)

You can leave "sentence" in the python script... that's needed for the GKSU fallback anyway and it's picked up by makepot. If that matches the same string in the polkit file, you don't need to make makepot parse polkit at all.

**Comment by clefebvre** [comment]
by the way, I see some of these PRs extend to Cinnamon also.

In that case, rather than making this specific to Linux Mint, we should do it in the scope of Xapps.

We want to introduce a Python library for xapps for other reasons anyway (some widgets are being duplicated all over the place, between Mint apps and Xapps and Cinnamon settings..) so this would be the place to do that.

We should chat about this on IRC when we get the opportunity.

**Comment by clefebvre** [comment]
https://github.com/linuxmint/mintsources/commit/3cb0f07236805937b5af9ebd260d09761a1f90ca

**Comment by clefebvre** [comment]
I'm still not 100% happy with this.. 

in LMDE gksu is able to remember the authorization.

This fails with pkexec.

The option auth_admin_keep only seems to work when pkexec is called by the user directly. When calling a script which calls pkexec, the authorization is asked every single time.

**Comment by AsciiWolf** [comment]
Any news regarding the pkexec support in Linux Mint?

**Comment by AsciiWolf** [comment]
Any news regarding the pkexec support in Linux Mint?

**Pull request closed without merging**
